export const portfolioDetailsData = [
  {
    id: 1,
    title: "E-commerce Platform",
    category: "Web Development",
    description:
      "A comprehensive e-commerce solution built with modern technologies, featuring advanced product management, secure payment processing, and real-time inventory tracking. The platform includes admin dashboard, customer management, order processing, and detailed analytics.",
    fullDescription:
      "This e-commerce platform represents a complete digital commerce solution designed for modern businesses. Built with React and Node.js, it features a responsive design that works seamlessly across all devices. The platform includes advanced features such as product catalog management, shopping cart functionality, secure payment processing through Stripe, order management system, customer accounts, and comprehensive admin dashboard with analytics and reporting capabilities.",
    image:
      "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    technologies: [
      "React",
      "Node.js",
      "MongoDB",
      "Stripe",
      "Express.js",
      "JWT",
      "Tailwind CSS",
      "Redux",
    ],
    features: [
      "Responsive design for all devices",
      "Secure payment processing",
      "Real-time inventory management",
      "Admin dashboard with analytics",
      "Customer account management",
      "Order tracking system",
      "Product catalog with search and filters",
      "Email notifications",
    ],
    liveUrl: "https://example-ecommerce.com",
    githubUrl: "https://github.com/example/ecommerce",
    client: "E-Commerce Solutions Inc.",
    duration: "3 months",
    year: "2024",
  },
  {
    id: 2,
    title: "Mobile Banking App",
    category: "Mobile Development",
    description:
      "A secure banking application with biometric authentication, real-time transactions, and comprehensive financial management tools.",
    fullDescription:
      "This mobile banking application provides users with a secure and intuitive way to manage their finances on the go. Built with React Native, it features biometric authentication, real-time transaction processing, account management, bill payments, and financial analytics. The app prioritizes security with end-to-end encryption and follows banking industry standards.",
    image:
      "https://images.unsplash.com/photo-1563013544-824ae1b704d3?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    technologies: [
      "React Native",
      "Firebase",
      "Redux",
      "Biometric API",
      "Encrypted Storage",
      "Push Notifications",
    ],
    features: [
      "Biometric authentication (Face ID/Touch ID)",
      "Real-time transaction processing",
      "Account balance and history",
      "Bill payment functionality",
      "Money transfer between accounts",
      "Financial analytics and insights",
      "Push notifications for transactions",
      "Secure encrypted data storage",
    ],
    liveUrl: "https://apps.apple.com/banking-app",
    githubUrl: null,
    client: "SecureBank Financial",
    duration: "4 months",
    year: "2024",
  },
  {
    id: 3,
    title: "Corporate Website",
    category: "Web Design",
    description:
      "Professional corporate website with modern design, optimized performance, and comprehensive business showcase.",
    fullDescription:
      "A modern corporate website designed to showcase business services and establish strong online presence. Built with React and optimized for performance, the website features responsive design, SEO optimization, content management capabilities, and integration with business tools. The design emphasizes professionalism while maintaining user-friendly navigation.",
    image:
      "https://images.unsplash.com/photo-1460925895917-afdab827c52f?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    technologies: [
      "React",
      "Tailwind CSS",
      "Vite",
      "Vercel",
      "Framer Motion",
      "React Router",
    ],
    features: [
      "Responsive and mobile-first design",
      "SEO optimized for search engines",
      "Fast loading performance",
      "Contact form integration",
      "Service showcase sections",
      "Team and about pages",
      "Blog/news section",
      "Social media integration",
    ],
    liveUrl: "https://example-corporate.com",
    githubUrl: "https://github.com/example/corporate",
    client: "Global Tech Corp",
    duration: "2 months",
    year: "2023",
  },
  {
    id: 4,
    title: "CRM System",
    category: "Software Development",
    description:
      "Custom CRM solution for business management with analytics, reporting, and customer relationship tools.",
    fullDescription:
      "A comprehensive Customer Relationship Management system designed to help businesses manage their customer interactions, sales pipeline, and business processes. Built with Vue.js and Laravel, it provides powerful tools for lead management, sales tracking, customer communication, and business analytics.",
    image:
      "https://images.unsplash.com/photo-1551434678-e076c223a692?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    technologies: [
      "Vue.js",
      "Laravel",
      "MySQL",
      "Chart.js",
      "PHP",
      "Vuex",
      "Bootstrap",
    ],
    features: [
      "Lead and customer management",
      "Sales pipeline tracking",
      "Task and appointment scheduling",
      "Email integration and templates",
      "Reporting and analytics dashboard",
      "Team collaboration tools",
      "Document management",
      "Mobile responsive interface",
    ],
    liveUrl: "https://example-crm.com",
    githubUrl: "https://github.com/example/crm",
    client: "Sales Pro Solutions",
    duration: "5 months",
    year: "2023",
  },
  {
    id: 5,
    title: "Learning Management System",
    category: "Web Development",
    description:
      "Educational platform with interactive features, progress tracking, and comprehensive learning tools.",
    fullDescription:
      "An advanced Learning Management System designed for educational institutions and corporate training. Built with Next.js and modern web technologies, it provides comprehensive tools for course creation, student management, progress tracking, and interactive learning experiences.",
    image:
      "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    technologies: [
      "Next.js",
      "PostgreSQL",
      "Prisma",
      "WebRTC",
      "Socket.io",
      "Tailwind CSS",
    ],
    features: [
      "Course creation and management",
      "Student enrollment and tracking",
      "Interactive video lessons",
      "Real-time chat and discussions",
      "Assignment and quiz system",
      "Progress tracking and analytics",
      "Certificate generation",
      "Mobile learning support",
    ],
    liveUrl: "https://example-lms.com",
    githubUrl: "https://github.com/example/lms",
    client: "EduTech Academy",
    duration: "6 months",
    year: "2024",
  },
  {
    id: 6,
    title: "Restaurant App",
    category: "Mobile Development",
    description:
      "Food ordering and delivery mobile application with real-time tracking and payment integration.",
    fullDescription:
      "A comprehensive food ordering and delivery application that connects customers with restaurants. Built with Flutter for cross-platform compatibility, it features real-time order tracking, multiple payment options, restaurant management tools, and delivery coordination.",
    image:
      "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    technologies: [
      "Flutter",
      "Firebase",
      "Google Maps",
      "Payment Gateway",
      "Push Notifications",
      "Dart",
    ],
    features: [
      "Restaurant browsing and search",
      "Menu management for restaurants",
      "Real-time order tracking",
      "Multiple payment options",
      "Delivery route optimization",
      "Customer reviews and ratings",
      "Push notifications for order updates",
      "Admin panel for restaurant management",
    ],
    liveUrl: "https://play.google.com/restaurant-app",
    githubUrl: "https://github.com/example/restaurant",
    client: "FoodHub Delivery",
    duration: "4 months",
    year: "2024",
  },
];
