export const pricingPlans = [
  {
    id: 1,
    title: "Starter",
    subtitle: "Static Website",
    price: "5,000",
    period: "one-time",
    description: "Perfect for small businesses and personal websites",
    features: [
      "5 Web Pages",
      "Free Domain (1 Year)",
      "Free Hosting (1 Year)",
      "Fully Responsive Design",
      "Basic SEO Setup",
      "Contact Form Integration",
    ],
    highlighted: false,
  },
  {
    id: 2,
    title: "Professional",
    subtitle: "Dynamic Website",
    price: "10,000",
    period: "one-time",
    description: "Ideal for growing businesses with dynamic content",
    features: [
      "6 Web Pages",
      "Free Domain & Hosting (1 Year)",
      "Fully Responsive Design",
      "Content Management System",
      "Advanced SEO Setup",
      "Contact Form Integration",
      "Social Media Integration",
      "Google Analytics Setup",
    ],
    highlighted: true,
    badge: "Most Popular",
  },
  {
    id: 3,
    title: "Enterprise",
    subtitle: "SEO Optimized Website",
    price: "25,000",
    period: "one-time",
    description: "Complete solution for businesses targeting growth",
    features: [
      "12 Web Pages",
      "50+ Locations SEO",
      "Free Domain & Hosting (1 Year)",
      "Fully Responsive Design",
      "Advanced CMS",
      "Premium SEO Package",
      "Social Media Integration",
      "Google Analytics & Search Console",
      "Monthly Performance Reports",
    ],
    highlighted: false,
  },
];
